version: "3.6"

services:
  nextjs:
    container_name: moon-base
    restart: always
    ports:
      - 3000:3000
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ../.env.local.docker
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'